# Generated by Django 6.0.2 on 2026-05-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/%Y/%m/%d/'),
        ),
    ]
